name = "AugustMC"
author = "A8gust"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f16fc3a6b3826404b4d37dad509d0dda6b9279b10b029398e484922a1a5dd289"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
