name = "AugustMC"
author = "A8gust"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c6057fd352690ab451b7e6e5c58a89ceae39c8c39283956243d70b402e673d4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
