name = "AugustMC"
author = "A8gust"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef993a9d885ccc55e44f6826f1dfb31b5e4649cf558b335970b1a2527ff91ceb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
