enable = true
enableDebugWindow = false

[windowGroup]
	enableWindow = true
	disableNames = []
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	windowMoveDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	windowMoveEase = "OUT_BACK"
	# Default: 0.0
	# Range: -10000.0 ~ 10000.0
	windowMoveX = 0.0
	# Default: 50.0
	# Range: -10000.0 ~ 10000.0
	windowMoveY = 50.0
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	windowGradientDuration = 0.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	windowGradientEase = "IN_OUT_SINE"
	enableJeiLeft = true
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	jeiLeftMoveDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	jeiLeftMoveEase = "OUT_BACK"
	# Default: -50.0
	# Range: -10000.0 ~ 10000.0
	jeiLeftMoveX = -50.0
	# Default: 0.0
	# Range: -10000.0 ~ 10000.0
	jeiLeftMoveY = 0.0
	enableJeiRight = true
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	jeiRightMoveDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	jeiRightMoveEase = "OUT_BACK"
	# Default: 50.0
	# Range: -10000.0 ~ 10000.0
	jeiRightMoveX = 50.0
	# Default: 0.0
	# Range: -10000.0 ~ 10000.0
	jeiRightMoveY = 0.0
	enableCloseWindow = false
	# Default: 1.5
	# Range: 0.0 ~ 1000.0
	closeWindowSpeed = 1.5

[screenItemGroup]
	enableHover = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	hoverDuration = 4.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	hoverEase = "IN_OUT_SINE"
	# Default: 1.2
	# Range: 1.0 ~ 10.0
	hoverScale = 1.2
	enableTooltip = true
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	tooltipDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	tooltipEase = "OUT_CIRC"
	# Default: 1.2
	# Range: 0.0 ~ 1000.0
	clickItemScale = 1.2
	enableClickItem = true
	# Default: 0.2
	# Range: 0.0 ~ 1000.0
	clickZoomStrength = 0.2
	# Default: 5.0
	# Range: 0.0 ~ 1000.0
	clickItemDuration = 5.0
	enableOutput = true
	# Default: 5.0
	# Range: 0.0 ~ 1000.0
	outputDuration = 5.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	outputEase = "OUT_BACK"
	enableDrag = true
	# Default: 15.0
	# Range: 0.0 ~ 90.0
	dragMaxAngle = 15.0
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	dragSensitivity = 8.0
	enableSameItem = true
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	sameItemDelay = 8.0
	# Default: 1.5
	# Range: 0.0 ~ 1000.0
	sameItemShakeStrength = 1.5
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	sameItemShakeDuration = 8.0
	# Default: 1.0
	# Range: 0.0 ~ 1000.0
	sameItemShakeFrequency = 1.0
	# Default: 20.0
	# Range: 0.0 ~ 1000.0
	sameItemShakeWaitDuration = 20.0
	enableQuick = true

[hotbarGroup]
	enableHoldItem = true
	enableHoldZoomTransition = false
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	holdZoomInDuration = 8.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	holdZoomInEase = "OUT_QUINT"
	# Default: 1.4
	# Range: 1.0 ~ 10.0
	holdZoomScale = 1.15
	# Default: 2.0
	# Range: 0.0 ~ 1000.0
	holdZoomOutDuration = 2.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	holdZoomOutEase = "OUT_QUART"
	enableSelectedItemName = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	selectedItemNameMoveDuration = 4.0
	# Default: 5.0
	# Range: 0.0 ~ 1000.0
	selectedItemNameMoveY = 5.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	selectedItemNameMoveEase = "IN_OUT_SINE"
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	selectedItemNameAlphaDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	selectedItemNameAlphaEase = "IN_OUT_SINE"
	enableAttack = true
	# Default: 15.0
	# Range: 0.0 ~ 90.0
	attackMaxAngle = 15.0
	enableUse = false
	# Default: 0.20000000298023224
	# Range: 0.0 ~ 1000.0
	useStrength = 0.20000000298023224
	enableLack = false
	# Default: 8.0
	# Range: 0.0 ~ 1000.0
	lackDuration = 8.0
	# Default: 3.0
	# Range: 0.0 ~ 1000.0
	lackShakeStrength = 3.0
	enableSelectMove = false
	# Default: 1.5
	# Range: 0.0 ~ 1000.0
	selectMoveSpeed = 1.5
	enableExp = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	expDuration = 4.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	expEase = "OUT_BACK"
	# Default: 4.0
	# Range: 1.0 ~ 1000.0
	expScale = 4.0
	enableArmor = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	armorDuration = 4.0
	# Default: 1.5
	# Range: 0.0 ~ 1000.0
	upArmorScale = 1.5
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	upArmorEase = "IN_OUT_SINE"
	# Default: 3.0
	# Range: 0.0 ~ 1000.0
	downArmorShakeStrength = 3.0

[chatGroup]
	enableChat = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	chatOpenMoveDuration = 4.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	chatOpenMoveEase = "IN_OUT_SINE"
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	chatOpenGradientDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	chatOpenGradientEase = "IN_OUT_SINE"
	enableChatComp = true
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	chatCompMoveDuration = 4.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	chatCompMoveEase = "IN_OUT_SINE"
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	chatCompGradientDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	chatCompGradientEase = "IN_OUT_SINE"
	enableCloseChat = true
	# Default: 1.2000000476837158
	# Range: 0.0 ~ 1000.0
	closeChatSpeed = 1.2000000476837158

[bossGroup]
	enableBossShow = true
	# Default: 10.0
	# Range: 0.0 ~ 1000.0
	bossShowDuration = 10.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	bossShowEase = "IN_OUT_SINE"
	# Default: 10.0
	# Range: 0.0 ~ 1000.0
	bossShowFadeDuration = 10.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	bossShowFadeEase = "IN_OUT_SINE"
	enableBossHide = true
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	bossHideDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	bossHideEase = "IN_OUT_SINE"
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	bossHideFadeDuration = 6.0
	#Allowed Values: LINEAR, IN_QUAD, OUT_QUAD, IN_OUT_QUAD, IN_CUBIC, OUT_CUBIC, IN_OUT_CUBIC, IN_QUART, OUT_QUART, IN_OUT_QUART, IN_QUINT, OUT_QUINT, IN_OUT_QUINT, IN_SINE, OUT_SINE, IN_OUT_SINE, IN_EXPO, OUT_EXPO, IN_OUT_EXPO, IN_CIRC, OUT_CIRC, IN_OUT_CIRC, IN_BACK, OUT_BACK, IN_OUT_BACK, IN_ELASTIC, OUT_ELASTIC, IN_OUT_ELASTIC, IN_BOUNCE, OUT_BOUNCE, IN_OUT_BOUNCE
	bossHideFadeEase = "IN_OUT_SINE"
	enableBossHurt = true
	# Default: 1.5
	# Range: 0.0 ~ 1000.0
	bossHurtShakeStrength = 1.5
	# Default: 4.0
	# Range: 0.0 ~ 1000.0
	bossHurtDuration = 4.0
