[mechanics]
	# Default: 120.0
	# Range: 1.0 ~ 1.0E7
	maxForce = 120.0
	# Default: 2.0
	# Range: 0.1 ~ 1000.0
	minDistance = 2.0
	# Default: 0.01
	# Range: 0.0 ~ 1.0
	grabStabilization = 0.01
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	rotationStabilization = 0.5
	enableRotation = true
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	maxRotationSpeed = 0.2
	preventFastRotations = true
	creativeSuperStrength = true
	# Default: 2.0
	# Range: 1.0 ~ 100.0
	strength1Multiplier = 2.0
	# Default: 4.0
	# Range: 1.0 ~ 100.0
	strength2Multiplier = 4.0
	enableBarehandedAssembly = true
	# Default: 1.0
	# Range: 0.1 ~ 10.0
	barehandedAssemblySpeedMultiplier = 1.0
	# Default: 2.0
	# Range: 1.0 ~ 10.0
	barehandedAssemblyMaxDistance = 2.0

[grab_collisions]
	ignoreCollisionsGrabSelf = false
	ignoreCollisionsGrabOtherPlayers = false
	ignoreCollisionsGrabEntities = false
	ignoreCollisionsGrabEverything = false

[rotation_collisions]
	ignoreCollisionsRotationSelf = true
	ignoreCollisionsRotationOtherPlayers = true
	ignoreCollisionsRotationEntities = true
	ignoreCollisionsRotationEverything = false

[core_physics]
	# Default: 1000.0
	# Range: 1.0 ~ 100000.0
	stiffness = 1000.0
	# Default: 125.0
	# Range: 1.0 ~ 10000.0
	damping = 125.0
	# Default: 850.0
	# Range: 1.0 ~ 10000.0
	angularDamping = 850.0

[advanced_physics]
	# Default: 0.02
	# Range: 0.0 ~ 1.0
	rotationMassDamping = 0.02
	# Default: 3.5
	# Range: 0.0 ~ 50.0
	tensionSuspendThreshold = 3.5
	# Default: 9.0
	# Range: 0.0 ~ 100.0
	tensionBreakThreshold = 9.0
	# Default: 2.5
	# Range: 0.0 ~ 10.0
	maxPlayerVelocityYUp = 2.5
	# Default: -4.0
	# Range: -20.0 ~ 0.0
	maxPlayerVelocityYDown = -4.0
	# Default: 2.5
	# Range: 0.0 ~ 10.0
	maxPlayerVelocityXZ = 2.5
