# Default: 0.5
# Range: 0.1 ~ 1.0
verticalRotationSensitivity = 0.5
# Default: 0.5
# Range: 0.1 ~ 1.0
horizontalRotationSensitivity = 0.5
invertVerticalRotation = false
invertHorizontalRotation = false
rotateAroundCenter = false
preventMovementWhileRotating = true
preventAssemblyWhenMining = true
# Default: 0.05
# Range: 0.0 ~ 1.0
barehandedAssemblyMiningThreshold = 0.05
