models.1=1
nbt.1.equipment.head.id=exists:true

models.2=1
nbt.2.equipment.chest.id=exists:true

models.3=1
nbt.3.equipment.legs.id=exists:true

models.4=1
nbt.4.equipment.feet.id=exists:true

models.5=1
nbt.5.equipment.mainhand.id=exists:true

models.6=1 2
weights.6=1 1